plugins {
    id "java"
    id "maven-publish"
    id "signing"
    id "org.embulk.embulk-plugins" version "0.7.0"
}

repositories {
    mavenCentral()
}

group = "org.embulk"
version = "0.11.1-SNAPSHOT"
description = "Loads records from local files."

configurations {
    compileClasspath.resolutionStrategy.activateDependencyLocking()
    runtimeClasspath.resolutionStrategy.activateDependencyLocking()

    // No need to declare "embulkTestImplementation" explicitly as the sourceSet "embulkTest" is declared below.
    // No need to declare "embulkTestRuntime" explicitly as the sourceSet "embulkTest" is declared below.
    //
    // "embulkTestImplementation" should not ".extendsFrom testImplementation"
    // so that it won't include main and test in the top-level class loader.
    //
    // "embulkTestRuntime" should not ".extendsFrom testRuntime" similarly.
}

sourceSets {
    embulkTest {
        java {
            srcDir file("src/embulkTest/java")
        }
        resources.srcDir file("src/embulkTest/resources")

        compileClasspath += sourceSets.main.output
        runtimeClasspath += sourceSets.main.output
    }
}

tasks.withType(JavaCompile) {
    options.compilerArgs << "-Xlint:deprecation" << "-Xlint:unchecked"
    options.encoding = "UTF-8"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }

    withJavadocJar()
    withSourcesJar()
}

dependencies {
    compileOnly "org.embulk:embulk-spi:0.11"
    compileOnly "org.slf4j:slf4j-api:2.0.7"

    implementation "org.embulk:embulk-util-config:0.5.0"
    implementation "javax.validation:validation-api:2.0.1.Final"
    implementation platform("com.fasterxml.jackson:jackson-bom:2.16.2")
    implementation "com.fasterxml.jackson.core:jackson-annotations"
    implementation "com.fasterxml.jackson.core:jackson-core"
    implementation "com.fasterxml.jackson.core:jackson-databind"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jdk8"

    implementation "org.embulk:embulk-util-file:0.2.0"

    testImplementation "junit:junit:4.13.2"
    testImplementation "org.embulk:embulk-spi:0.11"
    testImplementation "org.embulk:embulk-core:0.10.50"
    testImplementation "org.embulk:embulk-deps:0.10.50"
    testImplementation "org.embulk:embulk-junit4:0.10.50"

    embulkTestImplementation project(":embulk-junit5-api")  // TODO: embulk-junit5-api depends on junit-jupiter-api transitively?
    embulkTestImplementation "org.junit.jupiter:junit-jupiter-api:5.11.0"

    embulkTestImplementation "org.embulk:embulk-util-config:0.5.0"
    embulkTestImplementation "javax.validation:validation-api:2.0.1.Final"
    embulkTestImplementation platform("com.fasterxml.jackson:jackson-bom:2.16.2")
    embulkTestImplementation "com.fasterxml.jackson.core:jackson-annotations"
    embulkTestImplementation "com.fasterxml.jackson.core:jackson-core"
    embulkTestImplementation "com.fasterxml.jackson.core:jackson-databind"
    embulkTestImplementation "com.fasterxml.jackson.datatype:jackson-datatype-jdk8"
    embulkTestImplementation "org.embulk:embulk-util-file:0.2.0"

    embulkTestRuntimeOnly project(":embulk-junit5-engine")

    // embulk-core can be loaded in the top-level class loader.
    embulkTestRuntimeOnly "org.embulk:embulk-core:0.11.5"

    // To access the Embulk core classes from the tests.
    embulkTestCompileOnly "org.embulk:embulk-core:0.11.5"

    // TODO: Confirm just 'embulkTestImplementation "org.embulk:embulk-core:0.11.5"' may be better?
}

embulkPlugin {
    mainClass = "org.embulk.input.file.LocalFileInputPlugin"
    category = "input"
    type = "file"
}

jar {
    metaInf {
        from rootProject.file("LICENSE")
    }
}

sourcesJar {
    metaInf {
        from rootProject.file("LICENSE")
    }
}

javadocJar {
    metaInf {
        from rootProject.file("LICENSE")
    }
}

// A safer and strict alternative to: "dependencies" (and "dependencies --write-locks")
//
// This task fails explicitly when the specified dependency is not available.
// In contrast, "dependencies (--write-locks)" does not fail even when a part the dependencies are unavailable.
//
// https://docs.gradle.org/8.7/userguide/dependency_locking.html#generating_and_updating_dependency_locks
task checkDependencies {
    notCompatibleWithConfigurationCache("The task \"checkDependencies\" filters configurations at execution time.")
    doLast {
        configurations.findAll { it.canBeResolved }.each { it.resolve() }
    }
}

publishing {
    publications {
         maven(MavenPublication) {
            groupId = project.group
            artifactId = project.name

            from components.java
             // javadocJar and sourcesJar are added by java.withJavadocJar() and java.withSourcesJar() above.
             // See: https://docs.gradle.org/current/javadoc/org/gradle/api/plugins/JavaPluginExtension.html

            pom {  // https://central.sonatype.org/pages/requirements.html
                packaging "jar"

                name = project.name
                description = project.description
                url = "https://www.embulk.org/"

                licenses {
                    license {
                        // http://central.sonatype.org/pages/requirements.html#license-information
                        name = "The Apache License, Version 2.0"
                        url = "https://www.apache.org/licenses/LICENSE-2.0.txt"
                        distribution = "repo"
                    }
                }

                developers {
                    developer {
                        name = "Sadayuki Furuhashi"
                        email = "frsyuki@gmail.com"
                    }
                    developer {
                        name = "Hiroyuki Sato"
                        email = "hiroysato@gmail.com"
                    }
                    developer {
                        name = "Muga Nishizawa"
                        email = "muga.nishizawa@gmail.com"
                    }
                    developer {
                        name = "Dai MIKURUBE"
                        email = "dmikurube@acm.org"
                    }
                    developer {
                        name = "Koji Arai"
                        email = "jca02266@gmail.com"
                    }
                    developer {
                        name = "Satoshi Akama"
                        email = "satoshiakama@gmail.com"
                    }
                }

                scm {
                    connection = "scm:git:git://github.com/embulk/embulk-input-file.git"
                    developerConnection = "scm:git:git@github.com:embulk/embulk-input-file.git"
                    url = "https://github.com/embulk/embulk-input-file"
                }
            }
        }
    }

    repositories {
        maven {  // publishMavenPublicationToMavenCentralRepository
            name = "mavenCentral"
            if (project.version.endsWith("-SNAPSHOT")) {
                url "https://oss.sonatype.org/content/repositories/snapshots"
            } else {
                url "https://oss.sonatype.org/service/local/staging/deploy/maven2"
            }

            credentials {
                username = project.hasProperty("ossrhUsername") ? ossrhUsername : ""
                password = project.hasProperty("ossrhPassword") ? ossrhPassword : ""
            }
        }
    }
}

signing {
    if (project.hasProperty("signingKey") && project.hasProperty("signingPassword")) {
        logger.lifecycle("Signing with an in-memory key.")
        useInMemoryPgpKeys(signingKey, signingPassword)
    }
    sign publishing.publications.maven
}

test {
    testLogging {
        events "passed", "skipped", "failed", "standardOut", "standardError"
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
        showCauses = true
        showExceptions = true
        showStackTraces = true
        showStandardStreams = true
        outputs.upToDateWhen { false }
    }
}

task embulkTest(type: Test, dependsOn: ":assemble") {
    doFirst {
        println "^^^^^ Classpath information in main ^^^^^"
        println sourceSets.main.runtimeClasspath
        println sourceSets.main.runtimeClasspathConfigurationName
        sourceSets.main.runtimeClasspath.each {
            println it
        }
        println "^^^^^ Classpath information in embulkTest ^^^^^"
        println sourceSets.embulkTest.runtimeClasspath
        println sourceSets.embulkTest.runtimeClasspathConfigurationName
        sourceSets.embulkTest.runtimeClasspath.each {
            println it
        }
        println "^^^^^ Classpath information done ^^^^^"
    }

    useJUnitPlatform()

    // TODO See the following Gradle implementations to investigate Gradle classpath configurations.
    //
    // JavaPlugin.createDefaultTestSuite
    // https://github.com/gradle/gradle/blob/v8.10.1/platforms/jvm/plugins-java/src/main/java/org/gradle/api/plugins/JavaPlugin.java#L354-L383
    //
    // SourceSet.getRuntimeClasspathConfigurationName
    // https://github.com/gradle/gradle/blob/v8.10.1/platforms/jvm/platform-jvm/src/main/java/org/gradle/api/internal/tasks/DefaultSourceSet.java#L194-L197
    //
    // SourceSet.getRuntimeClasspath
    // https://github.com/gradle/gradle/blob/v8.10.1/platforms/jvm/platform-jvm/src/main/java/org/gradle/api/internal/tasks/DefaultSourceSet.java#L239-L242
    classpath = sourceSets.embulkTest.runtimeClasspath

    // Pick up "@EmbulkPluginTest" methods from the classes in "testClassesDirs"
    testClassesDirs = sourceSets.embulkTest.output.classesDirs

    afterEvaluate { project ->
        systemProperty "org.embulk.junit5.plugin.class.path",
                       joinPluginClasspath(sourceSets.embulkTest.output.classesDirs,
                                           sourceSets.embulkTest.output.resourcesDir,
                                           sourceSets.main.runtimeClasspath)
    }

    testLogging {
        events "started", "passed", "skipped", "failed", "standardOut", "standardError"
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
        showCauses = true
        showExceptions = true
        showStackTraces = true
        showStandardStreams = true
        outputs.upToDateWhen { false }
    }
}
